config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' } #sending_destinationテーブルに保存するため
  root 'home#index'
  resources :items do
    member do
      get :confirm
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    collection do
      get 'search'
      post 'pay/:id'=> 'items#pay', as: 'pay'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'update_done'
    end
  end

  resources :users do
    member do
      resources :profiles, only: [:new, :create, :edit, :update] 
    end
  end
  resources :cards, only: [:create, :new, :show, :destroy] 
end

app/views/template/_footer.html.haml
%aside.AppBanner
  .AppBannerInner
    %h2.AppBannerInner__title だれでもかんたん、人生を変えるフリマアプリ
    %p.AppBannerInner__text 今すぐ無料ダウンロード！
    .AppBannerInner__btn
      = link_to '#' do
        = image_tag 'http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg', alt: '', class: 'AppBannerInner__btn--aBtn'
      = link_to '#' do
        = image_tag 'http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg', alt: '', class: 'AppBannerInner__btn--gBtn'

.Footer
  %ul.FooterContents
    %li.FooterContents__content
      %h2.FooterContents__content__head FURIMAについて
      %ul.FooterContents__content__lists
        %li.FooterContents__content__lists__list
          = link_to"会社概要（運営会社）", "#", class: "FooterContents__content__lists__list__link"
        %li.FooterContents__content__lists__list
          = link_to"プライバシーポリシー", "#", class: "FooterContents__content__lists__list__link"
        %li.FooterContents__content__lists__list
          = link_to"FRIMA利用規約", "#", class: "FooterContents__content__lists__list__link"
        %li.FooterContents__content__lists__list
          = link_to"ポイントに関する特約", "#", class: "FooterContents__content__lists__list__link"
    %li.FooterContents__content
      %h2.FooterContents__content__head FURIMAを見る
      %ul.FooterContents__content__lists
        %li.FooterContents__content__lists__list
          = link_to"カテゴリー一覧", "#", class: "FooterContents__content__lists__list__link"
        %li.FooterContents__content__lists__list
          = link_to"ブランド一覧", "#", class: "FooterContents__content__lists__list__link"
    %li.FooterContents__content
      %h2.FooterContents__content__head ヘルプ＆ガイド
      %ul.FooterContents__content__lists
        %li.FooterContents__content__lists__list
          = link_to"FURIMAガイド", "#", class: "FooterContents__content__lists__list__link"
        %li.FooterContents__content__lists__list
          = link_to"FURIMAロゴ利用ガイドライン", "#", class: "FooterContents__content__lists__list__link"
        %li.FooterContents__content__lists__list
          = link_to"お知らせ", "#", class: "FooterContents__content__lists__list__link"
  .Footer__logo
    = link_to root_path do
      = image_tag 'logo-white.png', alt: 'logo', class: 'Footer__logo--img'
  %p © FURIMA

app/views/template/_header.html.haml
%header.Header
  .HeaderInner
    .HeaderInnerTop
      .HeaderInnerTop__icon
        = link_to root_path do
          = image_tag "logo.png", alt: "logo", class: 'HeaderInnerTop__icon--img'
      .HeaderInnerTop__searchBox
        = form_with(url: search_items_path, local: true, method: :get, class: "HeaderInnerTop__searchBox__form") do |f|
          = f.text_field :keyword, class: "HeaderInnerTop__searchBox__form__input", placeholder: "キーワードから探す"
          = button_tag type: 'submit', class: "HeaderInnerTop__searchBox__form__btn" do
            .HeaderInnerTop__searchBox__form__btn--icon
              = image_tag "icon-search 1.png", alt: "search_icon", class: 'HeaderInnerTop__searchBox__form__btn--icon--img'
              
    .HeaderInnerNav
      %ul.HeaderInnerNavlistsLeft
        %li.HeaderInnerNavlistsLeft__item
          .Categories
            %ul
              %li
                = link_to "#", class: "category__search search__btn" do
                  %i.fas.fa-bars.Category__icon
                  カテゴリーから探す
                %ul.Category__parent.Category__list
                  - @parents.each do |parent|
                    %li
                      = link_to "#", class: "Category__parent--name" do
                        = parent.name
                      %ul.Category__child.Category__list
                        - parent.children.each do |child|
                          %li
                            = link_to "#", class: "Category__child--name" do
                              = child.name
                            %ul.Category__grandchild.Category__list
                              - child.children.each do |grandchild|
                                %li
                                  = link_to "#", class: " Category__child--name" do
                                    = grandchild.name
                        
                        

      %ul.HeaderInnerNavlistsRight
      - if user_signed_in?
        %li.HeaderInnerNavlistsRight__item
          = link_to 'ログアウト', destroy_user_session_path, method: :delete
        %li.HeaderInnerNavlistsRight__item
          = link_to 'マイページ', user_path(current_user.id)
      - else
        %li.HeaderInnerNavlistsRight__item
          = link_to 'ログイン', new_user_session_path
        %li.HeaderInnerNavListsRight__item
          = link_to '新規会員登録', new_user_registration_path

app/views/template/_item.html.haml
- if user_signed_in?
  = link_to(new_item_path, {class: "PurchaseBtn"}) do
    .PurchaseBtn__box
      %span.PurchaseBtn__box__text 出品する
      = image_tag 'icon_camera.png', class: 'PurchaseBtn__box__icon'