config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' } #sending_destinationテーブルに保存するため
  root 'home#index'
  resources :items do
    member do
      get :confirm
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    collection do
      get 'search'
      post 'pay/:id'=> 'items#pay', as: 'pay'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'update_done'
    end
  end

  resources :users do
    member do
      resources :profiles, only: [:new, :create, :edit, :update] 
    end
  end
  resources :cards, only: [:create, :new, :show, :destroy] 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 7 }
  validates :first_name, presence: true, format: {with: /\A[ぁ-んァ-ン一-龥]/}
  validates :family_name, presence: true, format: {with: /\A[ぁ-んァ-ン一-龥]/}
  validates :first_name_kana, presence: true, format: {with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/}
  validates :family_name_kana, presence: true, format: {with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/}
  validates :birth_day, presence: true
  
  has_many :seller_items, foreign_key: "seller_id", class_name: "items"
  has_many :buyer_items, foreign_key: "buyer_id", class_name: "items"
  has_one :profile, dependent: :destroy
  has_one :sending_destination, dependent: :destroy
  # Userを通してsending_destinationに保存する
  accepts_nested_attributes_for :sending_destination
  has_one :card, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  def new
    @user = User.new
    @sending_destination = @user.build_sending_destination
    # @profile = @user.profile.user_id
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  before_action :set_category
  def index
  end

  def show
    @user = User.find(current_user.id)
    @profile = Profile.find_by(params[:id])
    @parents = Category.where(ancestry: nil)
    @items = Item.where(seller_id: @user).order(created_at: :desc)
    @items_length = @items.length
  end

  def edit
    @user = User.find(params[:id])
    @sending_destination = @user.sending_destination
  end

  def update
    if @user.update(user_params) && @sending_destination
      redirect_to @user
    else
      render :edit
    end
  end

  def destory
    @user.destory
    redirect_to root_path
  end

  private 
  def user_params
    params.require(:user).permit(
    :nickname,
    :first_name,
    :family_name,
    :first_name_kana,
    :family_name_kana,
    :birth_day,
    :destination_first_name,
    :destination_family_name,
    :destination_first_name_kana,
    :destination_family_name_kana,
    :post_code, 
    :prefecture_code,
    :city,
    :house_number,
    :building_name,
    :phone_number
    )
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_category
    @parents = Category.where(ancestry: nil)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
.Edit
  .Header
    .Header__logo
      = link_to root_path, class: "Header__logo--img" do
        = image_tag "logo.png",size: "140x50", alt: "icon"
  .Main
    %h1.Main__header 各種変更
    .Main__Container
      = form_for(@user) do |f|
        - if @user.errors.any?
          %h2= "#{@user.errors.full_messages.count}件のエラーが発生しました"
          %ul
            - @user.errors.full_messages.each do |message|
              %li= message
        .Main__Container__field
          .Main__Container__field__label
            %p ニックネーム
            %span.requier 必須
          = f.text_field :nickname, autofocus: true, autocomplete: "nickname", placeholder: '例：フリマ太郎', class: "Main__Container__field__input"
        .Main__Container__field
          .Main__Container__field__label
            %p メールアドレス
            %span.requier 必須
          = f.email_field :email, autocomplete: "email", placeholder: 'PC・携帯どちらでも可', class: "Main__Container__field__input"
        .Main__Container__field
          .Main__Container__field__label
            %p パスワード
            %span.requier 必須
          = f.password_field :password, autocomplete: "off" ,placeholder: '7文字以上の半角英数字', class: "Main__Container__field__input"
          %p.Main__Container__field__text ※英数字と数字の両方を含めて設定ください
        .Main__Container__field
          .Main__Container__field__label
            %p 確認用パスワード
            %span.requier 必須
          = f.password_field :password_confirmation, autocomplete: "new-password", placeholder: '上と同じパスワードを入力してください', class: "Main__Container__field__input"
        .Main__Container__field
          .Main__Container__field__label
            %p お名前
            %span.requier 必須
          = f.text_field :family_name, autocomplete: "family_name", placeholder: '例：山田', class: "Main__Container__field__input"
          = f.text_field :first_name, autocomplete: "first_name", placeholder: '例：太郎', class: "Main__Container__field__input"
        .Main__Container__field
          .Main__Container__field__label
            %p お名前カナ
            %span.requier 必須
          = f.text_field :family_name_kana, autocomplete: "family_name_kana", placeholder: '例：ヤマダ', class: "Main__Container__field__input"
          = f.text_field :first_name_kana, autocomplete: "first_name_kana", placeholder: '例：タロウ', class: "Main__Container__field__input"
        .Main__Container__field
          .Main__Container__field__label
            %p 生年月日
            %span.requier 必須
          = f.text_field :birth_day, autocomplete: "off", placeholder: '例：1986年01月01日→19860101', class: "Main__Container__field__input"
        = f.fields_for :sending_destination do |f|
          .Main__Container__field
            .Main__Container__field__label
              %p お届け先氏名
              %span.requier 必須
            = f.text_field :destination_family_name, autocomplete: "destination_family_name", placeholder: '例：山田', class: "Main__Container__field__input"
            = f.text_field :destination_first_name, autocomplete: "destination_first_name", placeholder: '例：太郎', class: "Main__Container__field__input"
          .Main__Container__field
            .Main__Container__field__label
              %p お届け先氏名カナ
              %span.requier 必須
            = f.text_field :destination_family_name_kana, autocomplete: "destination_family_name_kana", placeholder: '例：ヤマダ', class: "Main__Container__field__input"
            = f.text_field :destination_first_name_kana, autocomplete: "destination_first_name_kana", placeholder: '例：タロウ', class: "Main__Container__field__input"
          .Main__Container__field
            .Main__Container__field__label
              %p 電話番号
              %span.requier 任意
            = f.text_field :phone_number, autocomplete: "phone_number", placeholder: '例：080XXXXXXXX', class: "Main__Container__field__input"  
          .Main__Container__field
            .Main__Container__field__label
              %p 郵便番号
              %span.requier 必須
            = f.text_field :post_code, autocomplete: "post_code", placeholder: '例：1234567', class: "Main__Container__field__input"
          .Main__Container__field
            .Main__Container__field__label
              %p 都道府県
              %span.requier 必須
            = f.collection_select :prefecture_code_id, PrefectureCode.all, :id, :name,{selected: 0}, {class: "Main__Container__field__inputs"}
          .Main__Container__field
            .Main__Container__field__label
              %p 市区町村
              %span.requier 必須
            = f.text_field :city, autocomplete: "city", placeholder: '例：市区町村', class: "Main__Container__field__input"
          .Main__Container__field
            .Main__Container__field__label
              %p 番地
              %span.requier 必須
            = f.text_field :house_number, autocomplete: "house_number", placeholder: '例：番地', class: "Main__Container__field__input"
          .Main__Container__field
            .Main__Container__field__label
              %p 建物名
              %span.option 任意
            = f.text_field :building_name, autocomplete: "building_name", placeholder: '例：フリママンション101号室', class: "Main__Container__field__input"
          
        .Main__Container__actions
          = f.submit "変更する", class: "Main__Container__actions__submit"
  = render 'template/footer'

app/views/users/show.html.haml
= render 'template/header'
.Back
  .User
    .User__image
      = link_to user_path(current_user.id) do
        = image_tag 'bg-appBanner-pict.jpg', alt: 'sample'
      .User__image__name
        - if @user.profile.present? && @user.profile.avatar.present?
          = image_tag @user.profile.avatar.url
        - else
          = @user.nickname
      .User__image__edit
        .User__image__edit__items
          出品数:
          = @items_length
        .User__image__edit__mypage
          = link_to '編集', edit_user_path(@user)
    .User__card
      .User__card__new
        = link_to 'カードの登録', new_card_path
      .User__card__edit
        = link_to 'カードの詳細', card_path
    .User__introduction
      - if @user.profile.present? && @user.profile.introduce?
        = @user.profile.introduce
      - else
        = "自己紹介文はありません"
    .User__action
      - if @user.profile.present?
        = link_to "変更する", edit_profile_path(@profile), class: 'User__action__button'
      - else
        = link_to "設定する", new_profile_path, class: 'User__action__button'
    .User__item
      %h1 この出品者の商品
    .User__items
      - @items.each do |item|
        = render 'items/item', item: item

= render 'template/item'
= render 'template/footer'