config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' } #sending_destinationテーブルに保存するため
  root 'home#index'
  resources :items do
    member do
      get :confirm
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    collection do
      get 'search'
      post 'pay/:id'=> 'items#pay', as: 'pay'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'update_done'
    end
  end

  resources :users do
    member do
      resources :profiles, only: [:new, :create, :edit, :update] 
    end
  end
  resources :cards, only: [:create, :new, :show, :destroy] 
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :seller, class_name: "User"
  has_one :buyer, class_name: "User"
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true
  belongs_to :category
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture_code

  validates :name,presence: true
  validates :introduction,presence: true
  validates :price,presence: true
  validates :item_condition,presence: true
  validates :postage_payer,presence: true
  validates :prefecture_code,presence: true
  validates :preparation_day,presence: true
  validates :postage_type,presence: true
  validates :category_id,presence: true
  validates :trading_status,presence: true
  validates :seller_id,presence: true

  #配送状況
  enum trading_status: { 
                          '配送済み':0,
                          '輸送中':1,
                          '配達中':2,
                          '配達済み':3,
                          '調査中':4,
                        }
  #商品の状態
  enum item_condition: {
                          '新品、未使用':0,
                          '未使用に近い':1,
                          '目立った傷や汚れなし':2,
                          'やや傷や汚れあり':3,
                          '傷や汚れあり':4,
                          '全体的に状態が悪い':5,
                        }
  #配送料の負担
  enum postage_payer: {
                        '送料込み':0,
                        '着払い':1,
                      }
  #発送までの日数
  enum preparation_day: { 
                        '1~2日で発送':0,
                        '2~3日で発送':1,
                        '4~7日で発送':2,
                      }
  #配送の方法
  enum postage_type: { 
                      '未定':0,
                      '宅急便':1,
                      '郵便':2
                    }

  def self.search(search)
    return Item.all unless search
    Item.where('name LIKE(?)', "%#{search}%")
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_categorie
  def index
    @parents = Category.where(ancestry: nil)
  end

  def new
    @item = Item.new
    @item.item_images.new
    @category_parent_array = ["選択してください"] #セレクトボックスの初期値設定
    Category.where(ancestry: nil).each do |parent| #データベースから、親カテゴリーのみ抽出し、配列化
      @category_parent_array << parent.name
    end
  end
  # 以下全て、formatはjsonのみ
  def get_category_children # 親カテゴリーが選択された後に動くアクション
    @category_children = Category.find_by(name: "#{params[:parent_name]}").children #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
  end

  def get_category_grandchildren # 子カテゴリーが選択された後に動くアクション
    @category_grandchildren = Category.find("#{params[:child_id]}").children #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
  end

  def create
    @item = Item.new(item_params)
    @category_id = @item.category_id
    if @item.item_images.present?
      if @item.save
        redirect_to root_path
      else
        redirect_to action: :new
      end
    else
      redirect_to action: :new
    end
  end

  def confirm
    @item = Item.find(params[:id])
    @card = Card.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to new_card_path
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
      @user = User.find(current_user.id)
    end
  end

  def show
    @item = Item.find(params[:id])
    @grandChild_category = Category.find(@item.category_id)
    @child_category = @grandChild_category.parent
    @parent_category = @child_category.parent
  end

  def pay
    @item = Item.find(params[:id])
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to new_card_path
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      Payjp::Charge.create(
        amount: @item.price,
        customer: card.customer_id,
        currency: 'jpy' #通貨
      )
      @item.update( buyer_id: current_user.id )
      redirect_to root_path
    end
  end


  def edit
    @item = Item.find(params[:id])
    grandchild_category = @item.category
    child_category = grandchild_category.parent
    
    @category_parent_array = []
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end

    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
      @category_children_array << children
    end

    @category_grandchildren_array = []
    Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end
    
    
  end

  def update
    @item = Item.find(params[:id])
    length = @item.item_images.length
    i = 0
    while i < length do
      if  item_update_params[:item_images_attributes]["#{i}"]["_destroy"] == "0"
        @item.update(item_update_params)
        redirect_to update_done_items_path
        return
      else
        i += 1
      end
    end
    if item_update_params[:item_images_attributes]["#{i}"]
      @item.update(item_update_params)
    end
    redirect_to edit_item_path(@item.id)
    return
  end

  def update_done
    @item_update = Item.order("updated_at DESC").first
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to root_path
  end

  def search
    @items = Item.search(params[:keyword])
  end

  private
  def item_params
    params.require(:item).permit(
      :name,
      :introduction,
      :item_condition,
      :postage_payer,
      :prefecture_code_id,
      :preparation_day,
      :price,
      :category_id,
      item_images_attributes: [:id, :url, :_destroy]
      )
      .merge(
        seller_id: current_user.id
      )
  end

  def item_update_params
    params.require(:item).permit(
      :name,
      :introduction,
      :item_condition,
      :postage_payer,
      :prefecture_code_id,
      :preparation_day,
      :price,
      :category_id,
      :image_cache,
      item_images_attributes: [:id, :_destroy, :url]
    ).merge(
      seller_id: current_user.id
    )
  end

  def set_categorie
    @parents = Category.where(ancestry: nil)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.haml
.MainPickupProductBoxProductLists__list
  = link_to item_path(item.id) do
    %figure.MainPickupProductBoxProductLists__list--img
      = image_tag item.item_images.first.url.url, alt: '', class: 'MainPickupProductBoxProductLists__list--img--pict'
      - if item.buyer_id.present?
        .MainPickupProductBoxProductLists__list--img--buy
          %p SOLD
    .MainPickupProductBoxProductLists__list--body
      %h3.MainPickupProductBoxProductLists__list--body--name
        = item.name
      .MainPickupProductBoxProductLists__list--body--details
        %ul.MainPickupProductBoxProductLists__list--body__details--ul
          %li= "#{item.price}円"
          %li
            %i.fa.fa-star.likeIcon
            0
        %p (税込)

app/views/items/confirm.html.haml
%body.Buy
  %header.BuyTop
    .BuyTop__icon
      = link_to root_path do
        = image_tag "logo.png", alt: "logo", class: 'BuyTop__icon--img'

  %main.BuyMain
    .BuyMainConfirm
      .BuyMainConfirmContainer
        %h2.BuyMainConfirmContainer__title
          購入内容の確認
        .BuyMainConfirmContainer__info
          %figure.BuyMainConfirmContainer__info__figure
            = image_tag @item.item_images.first.url.url, alt: '商品のイメージ画像', class: 'BuyMainConfirmContainer__info__figure__img'
          .BuyMainConfirmContainer__info__box
            %p.BuyMainConfirmContainer__info__box__text
              = @item.name
            %p.BuyMainConfirmContainer__info__box__price
              %span.BuyMainConfirmContainer__info__box__price__taxIn
                送料込み（税込）
              %span.BuyMainConfirmContainer__info__box__price__number
                = "¥#{@item.price}"
        .BuyMainConfirmContainer__payment
          %span.BuyMainConfirmContainer__payment__text
            支払い金額
          %span.BuyMainConfirmContainer__payment__number
            = "¥#{@item.price}"
        .BuyMainConfirmContainer__payWay
          %h3.BuyMainConfirmContainer__payWay__title
            支払い方法
          = link_to("変更する ", '#', {class: "BuyMainConfirmContainer__payWay__edit"})
        .BuyMainConfirmContainer__cardData
          %p 
            クレジットカード
          %p
            = "**** **** **** " + @default_card_information.last4
          %p
            有効期限
          %p
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
          = image_tag 'https://pcweb-assets.mercdn.net/assets/img/card/visa.svg?2269318488', alt: 'visa', height: '20px', width: '50px', class: 'BuyMainConfirmContainer__cardData__img'
        .BuyMainConfirmContainer__postageType
          %h3.SellMainConfirmContainer__postageType__title
            配送方法
          = link_to("変更する", '#', {class: "BuyMainConfirmContainer__postageType__edit"})
        .BuyMainConfirmContainer__postData
          %p 
            = @user.sending_destination.post_code
          %p
            = "#{@user.sending_destination.prefecture_code[:name]} #{@user.sending_destination.city} #{@user.sending_destination.house_number} #{@user.sending_destination.building_name}"
          %p
            = @user.nickname
        .BuyMainConfirmContainer__btn
          = form_tag(action: :pay, method: :post) do
            %button(type="submit" class="BuyMainConfirmContainer__btn__submit")
              購入する


  %footer.BuyBottom
    .BuyBottomContents
      %ul.BuyBottomContents__lists
        %li.BuyBottomContents__lists__list
          = link_to 'プライバシーポリシー', '#'
        %li.BuyBottomContents__lists__list
          = link_to 'メルカリ利用規約', '#'
        %li.BuyBottomContents__lists__list
          = link_to '特定商取引に関する表記', '#'
    .BuyBottomLogo
      = link_to root_path do
        = image_tag 'logo.png', alt: 'logo', class: 'BuyBottomLogo--img'
    %p.BuyBottom__copyright
      © FURIMA

app/views/items/edit.html.haml
%body.Sell
  %header.SellTop
    .SellTop__icon
      = link_to root_path do
        = image_tag "logo.png", alt: "logo", class: 'SellTop__icon--img'
  
  %main.SellMain
    = form_with model: @item, class: "SellMainForm", local: true do |f|
      .SellMainFormContainer
        .SellMainFormContainer__title
          %h3.SellMainFormContainer__title--text
            出品画像
          %span.SellMainFormContainer__title--require
            必須
        %p.SellMainFormContainer__note
          最大5枚までアップロードできます
        .post__drop__box__container
          .prev-content
            - @item.item_images.each do |image|
              .preview-box
                .upper-box
                  = image_tag image.url.url, width: "112", height: "112", alt: "preview"
                .lower-box
                  .update-box
                    %label.edit-btn 編集
                  .delete-box
                    .delete-btn
                      %span 削除
          .label-content
            = f.label :"item_images_attributes_#{@item.item_images.length}_url", class: "label-box", id: "label-box--#{@item.item_images.length}" do
              %pre.label-box__text-visible クリックしてファイルをアップロード
          .hidden-content
            = f.fields_for :item_images do |i|
              = i.file_field :url, class: "hidden-field"
              = i.check_box :_destroy, class: "hidden-checkbox" 
            - @item.item_images.length.upto(4) do |i|
              %input{name: "item[item_images_attributes][#{i}][url]", id: "item_item_images_attributes_#{i}_url", class:"hidden-field", type:"file"}

      .SellMainFormContainer
        .SellMainFormContainer__title
          %h3.SellMainFormContainer__title--text
            商品名
          %span.SellMainFormContainer__title--require
            必須
        .SellMainFormContainer__itemName
          = f.text_field :name, {placeholder: "40文字まで", class: "SellMainFormContainer__itemName__field"}

      .SellMainFormContainer
        .SellMainFormContainer__title
          %h3.SellMainFormContainer__title--text
            商品の説明
          %span.SellMainFormContainer__title--require
            必須
        .SellMainFormContainer__itemExplanation
          = f.text_area :introduction, {id: "input-text", class: "SellMainFormContainer__itemExplanation__field", placeholder: "例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでおすすめです。（1,000文字以内）（色、素材、重さ、定価、注意点など）"}
        .SellMainFormContainer__wordCount
          %p#counter
            0/1000

      .SellMainFormContainer
        .SellMainFormContainer__subTitle
          商品の詳細
        .SellMainFormContainer__title
          %h3.SellMainFormContainer__title--text
            カテゴリー
          %span.SellMainFormContainer__title--require
            必須
        .SellMainFormContainer__select
          .SellMainFormContainer__select__area
            .SellMainFormContainer__select__area__wrapper
              .SellMainFormContainer__select__area__wrapper__box
                = f.select :parent_name, @category_parent_array,{selected:@item.category.parent.parent.name},{class: 'SellMainFormContainer__select__area__wrapper__box--select',id:'parent_category'}
            .SellMainFormContainer__select__area__wrapper#children_wrapper
              .SellMainFormContainer__select__area__wrapper__box
                = f.select :child_id, options_for_select(@category_children_array.map{|b|[b.name, b.id,{date:{category: b.id}}]},{prompt: "指定なし",selectd:@item.category.parent.id}),{},{class:'SellMainFormContainer__select__area__wrapper__box--select',id:'child_category'}
            .SellMainFormContainer__select__area__wrapper#grandchildren_wrapper
              .SellMainFormContainer__select__area__wrapper__box
                = f.select :category_id, options_for_select(@category_grandchildren_array.map{|b| [b.name, b.id,{data:{category: b.id}}]},{prompt:"指定なし",selected: @item.category.id}),{}, {class: 'SellMainFormContainer__select__area__wrapper__box--select',id:'grandchild_category'}
        .SellMainFormContainer__title
          %h3.SellMainFormContainer__title--text
            商品の状態
          %span.SellMainFormContainer__title--require
            必須
        .SellMainFormContainer__select
          = f.select :item_condition, Item.item_conditions.keys, {include_blank: "選択してください"}, {class: "SellMainFormContainer__select__field"}

      .SellMainFormContainer
        .SellMainFormContainer__subTitle
          発送について
        .SellMainFormContainer__title
          %h3.SellMainFormContainer__title--text
            発送料の負担
          %span.SellMainFormContainer__title--require
            必須
        .SellMainFormContainer__select
          = f.select :postage_payer, Item.postage_payers.keys, {include_blank: "選択してください"} , {class: "SellMainFormContainer__select__field"}
            
        .SellMainFormContainer__title
          %h3.SellMainFormContainer__title--text
            発送元の地域
          %span.SellMainFormContainer__title--require
            必須
        .SellMainFormContainer__select
          = f.collection_select :prefecture_code_id, PrefectureCode.all, :id, :name,{}, {class: "SellMainFormContainer__select__field"}
        .SellMainFormContainer__title
          %h3.SellMainFormContainer__title--text
            発送までの日数
          %span.SellMainFormContainer__title--require
            必須
        .SellMainFormContainer__select
          = f.select :preparation_day, Item.preparation_days.keys, {include_blank: "選択してください"}, {class: "SellMainFormContainer__select__field"}

      .SellMainFormContainer
        .SellMainFormContainer__subTitle
          価格（¥300〜9,999,999）
        .SellMainFormContainer__price
          %h3.SellMainFormContainer__price__title
            販売価格
          %span.SellMainFormContainer__price__require
            必須
          %span.SellMainFormContainer__price__ennMark
            ¥
          = f.number_field :price, placeholder: 0, min: 300, max: 9999999, class: "SellMainFormContainer__price__number"
        .SellMainFormContainer__tax
          .SellMainFormContainer__tax__text
            販売手数料（10%）
          .SellMainFormContainer__tax__bar
            ー
        %hr.SellMainFormContainer__bar/
        .SellMainFormContainer__tax
          .SellMainFormContainer__tax__text
            販売利益
          .SellMainFormContainer__tax__bottom
            ー
        .SellMainFormContainer__btn
          = f.submit "更新する", class: "SellMainFormContainer__btn__submit"
          = link_to("もどる", root_path, {class: "SellMainFormContainer__btn__back"})
        .SellMainFormContainer__note
          %p.SellMainFormContainer__note__text
            禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。


  %footer.SellBottom
    .SellBottomContents
      %ul.SellBottomContents__lists
        %li.SellBottomContents__lists__list
          = link_to 'プライバシーポリシー', '#'
        %li.SellBottomContents__lists__list
          = link_to 'メルカリ利用規約', '#'
        %li.SellBottomContents__lists__list
          = link_to '特定商取引に関する表記', '#'
    .SellBottomLogo
      = link_to root_path do
        = image_tag 'logo.png', alt: 'logo', class: 'SellBottomLogo--img'
    %p.SellBottom__copyright
      © FURIMA

app/views/items/new.html.haml
%body.Sell
  %header.SellTop
    .SellTop__icon
      = link_to root_path do
        = image_tag "logo.png", alt: "logo", class: 'SellTop__icon--img'
  
  %main.SellMain
    = form_with model: @item, class: "SellMainForm", local: true do |f|
      .SellMainFormContainer
        .SellMainFormContainer__title
          %h3.SellMainFormContainer__title--text
            出品画像
          %span.SellMainFormContainer__title--require
            必須
        %p.SellMainFormContainer__note
          最大5枚までアップロードできます
        .post__drop__box__container
          .prev-content
          .label-content
            %label{for: "item_item_images_attributes_0_url", class: "label-box", id: "label-box--0"}
              %pre.label-box__text-visible クリックしてファイルをアップロード
          .hidden-content
            = f.fields_for :item_images do |i|
              = i.file_field :url, class: "hidden-field"
              %input{class:"hidden-field", type: "file", name: "item[item_images_attributes][1][url]", id: "item_item_images_attributes_1_url" }
              %input{class:"hidden-field", type: "file", name: "item[item_images_attributes][2][url]", id: "item_item_images_attributes_2_url" }
              %input{class:"hidden-field", type: "file", name: "item[item_images_attributes][3][url]", id: "item_item_images_attributes_3_url" }
              %input{class:"hidden-field", type: "file", name: "item[item_images_attributes][4][url]", id: "item_item_images_attributes_4_url" }

      .SellMainFormContainer
        .SellMainFormContainer__title
          %h3.SellMainFormContainer__title--text
            商品名
          %span.SellMainFormContainer__title--require
            必須
        .SellMainFormContainer__itemName
          = f.text_field :name, {placeholder: "40文字まで", class: "SellMainFormContainer__itemName__field"}

      .SellMainFormContainer
        .SellMainFormContainer__title
          %h3.SellMainFormContainer__title--text
            商品の説明
          %span.SellMainFormContainer__title--require
            必須
        .SellMainFormContainer__itemExplanation
          = f.text_area :introduction, {id: "input-text", class: "SellMainFormContainer__itemExplanation__field", placeholder: "例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでおすすめです。（1,000文字以内）（色、素材、重さ、定価、注意点など）"}
        .SellMainFormContainer__wordCount
          %p#counter
            0/1000
      .SellMainFormContainer
        .SellMainFormContainer__subTitle
          商品の詳細
        .SellMainFormContainer__title
          %h3.SellMainFormContainer__title--text
            カテゴリー
          %span.SellMainFormContainer__title--require
            必須
        .SellMainFormContainer__select
          .SellMainFormContainer__select__area
            .SellMainFormContainer__select__area__wrapper
              .SellMainFormContainer__select__area__wrapper__box
                = f.select :category_id, @category_parent_array, {}, {class: 'SellMainFormContainer__select__area__wrapper__box--select', id: 'parent_category'}

        .SellMainFormContainer__title
          %h3.SellMainFormContainer__title--text
            商品の状態
          %span.SellMainFormContainer__title--require
            必須
        .SellMainFormContainer__select
          = f.select :item_condition, Item.item_conditions.keys, {include_blank: "選択してください", selected: 0}, {class: "SellMainFormContainer__select__field"}

      .SellMainFormContainer
        .SellMainFormContainer__subTitle
          発送について
        .SellMainFormContainer__title
          %h3.SellMainFormContainer__title--text
            発送料の負担
          %span.SellMainFormContainer__title--require
            必須
        .SellMainFormContainer__select
          = f.select :postage_payer, Item.postage_payers.keys, {include_blank: "選択してください", selected: 0} , {class: "SellMainFormContainer__select__field"}
            
        .SellMainFormContainer__title
          %h3.SellMainFormContainer__title--text
            発送元の地域
          %span.SellMainFormContainer__title--require
            必須
        .SellMainFormContainer__select
          = f.collection_select :prefecture_code_id, PrefectureCode.all, :id, :name,{selected: 0}, {class: "SellMainFormContainer__select__field"}
        .SellMainFormContainer__title
          %h3.SellMainFormContainer__title--text
            発送までの日数
          %span.SellMainFormContainer__title--require
            必須
        .SellMainFormContainer__select
          = f.select :preparation_day, Item.preparation_days.keys, {include_blank: "選択してください", selected: 0}, {class: "SellMainFormContainer__select__field"}

      .SellMainFormContainer
        .SellMainFormContainer__subTitle
          価格（¥300〜9,999,999）
        .SellMainFormContainer__price
          %h3.SellMainFormContainer__price__title
            販売価格
          %span.SellMainFormContainer__price__require
            必須
          %span.SellMainFormContainer__price__ennMark
            ¥
          = f.number_field :price, placeholder: 0, min: 300, max: 9999999, class: "SellMainFormContainer__price__number"
        .SellMainFormContainer__tax
          .SellMainFormContainer__tax__text
            販売手数料（10%）
          .SellMainFormContainer__tax__bar
            ー
        %hr.SellMainFormContainer__bar/
        .SellMainFormContainer__tax
          .SellMainFormContainer__tax__text
            販売利益
          .SellMainFormContainer__tax__bottom
            ー
        .SellMainFormContainer__btn
          = f.submit "出品する", class: "SellMainFormContainer__btn__submit"
          = link_to("もどる", root_path, {class: "SellMainFormContainer__btn__back"})
        .SellMainFormContainer__note
          %p.SellMainFormContainer__note__text
            禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。


  %footer.SellBottom
    .SellBottomContents
      %ul.SellBottomContents__lists
        %li.SellBottomContents__lists__list
          = link_to 'プライバシーポリシー', '#'
        %li.SellBottomContents__lists__list
          = link_to 'メルカリ利用規約', '#'
        %li.SellBottomContents__lists__list
          = link_to '特定商取引に関する表記', '#'
    .SellBottomLogo
      = link_to root_path do
        = image_tag 'logo.png', alt: 'logo', class: 'SellBottomLogo--img'
    %p.SellBottom__copyright
      © FURIMA

app/views/items/search.html.haml
= render 'template/header'
.SearchItems
  .Main
    .MainContainer
      .MainContainer__header
        %p.result 
          = params[:keyword]
        %h2 の検索結果
      .MainContainer__field
        - @items.each do |item|
          = render 'item', item: item
= render 'template/footer'

app/views/items/show.html.haml
= render 'template/header'
.ShowItems
  %section.Main
    .MainContainer
      .MainContainer__title
        %h1  
          = @item.name
      .MainContainer__item
        .MainContainer__item__image
          .main-content.clearfix
            .main-content__photo
              .owl-carousel.owl-loaded.owl-drag
                .owl-stage-outer
                  .owl-stage{ style: 'left:0px',width: '900px'}
                    - @item.item_images.each do |i|
                      - if i.url.present?
                        .owl-item{ style: 'width:300px'}
                          - if @item.buyer_id.present?
                            .MainPickupProductBoxProductLists__list--img--buy
                              %p SOLD
                          .owl-item__inner.is-higher-width
                            = image_tag i.url.url

                .owl-dots{ style: 'display:flex'}
                  - if @item.item_images.present?
                    - @item.item_images.each do |i|
                      .owl-dot
                        .owl-dot-inner{ style: 'display:flex'}
                          = image_tag i.url.url
              
        .MainContainer__item__table
          %table.TableBody
            %tr
              %th 出品者
              %td= link_to @item.seller.nickname,"#"
                  
            %tr
              %th カテゴリー
              %td#categories
                = link_to @parent_category.name,"#"
                = link_to @child_category.name,"#"
                = link_to @grandChild_category.name,"#"
              
            %tr
              %th 商品状態
              %td 
                = @item.item_condition
            %tr
              %th 配送料の負担
              %td 
                = @item.postage_payer
            %tr
              %th 配送の方法
              %td 
                =@item.postage_type
            %tr
              %th 配送元地域
              %td= link_to "#{@item.prefecture_code.name}","#"
                
            %tr
              %th 発送日の目安
              %td 
                =@item.preparation_day
      .MainContainer__pricebox
        %span.price 
          ¥
          =@item.price
        %span.tax (税込)
        %span.fee_side 送料込み
      %form.MainContainer__actions
        - if user_signed_in? && current_user.id != @item.seller.id
          - if @item.buyer_id == nil
            %button.MainContainer__actions--btn{type: "submit"}
              = link_to '購入画面に進む', confirm_item_path(@item)
        
          
      .MainContainer__description
        .MainContainer__description--text
          商品説明欄 
          %br
            =@item.introduction
      .MainContainer__EditDelete
        - if user_signed_in? && current_user.id == @item.seller.id
          .MainContainer__EditDelete--edit
            = link_to '編集', edit_item_path(@item)
          .MainContainer__EditDelete--delete
            = link_to '削除', item_path(@item), method: :delete
        
= render 'template/footer' 

app/views/items/update_done.html.haml
= render 'template/header.html.haml'
.done__edit
  .done__edit__title
    %h3 商品情報を更新しました
  .done__edit__toppage
    = link_to "トップページへ戻る",root_path,class: 'link'
  .done__edit__confirmation
    = link_to "更新した商品を確認する",item_path(@item_update),class: 'link'

= render 'template/footer'
= render 'template/item'