config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' } #sending_destinationテーブルに保存するため
  root 'home#index'
  resources :items do
    member do
      get :confirm
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    collection do
      get 'search'
      post 'pay/:id'=> 'items#pay', as: 'pay'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'update_done'
    end
  end

  resources :users do
    member do
      resources :profiles, only: [:new, :create, :edit, :update] 
    end
  end
  resources :cards, only: [:create, :new, :show, :destroy] 
end

app/models/card.rb
class Card < ApplicationRecord
  validates :customer_id, presence: true
  validates :card_id, presence: true
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require 'payjp'
  before_action :set_card, only:[:index, :show, :destroy]
  before_action :set_category

  def new
    @card = Card.where(user_id: current_user.id)
    redirect_to card_path(current_user.id) if @card.exists?
  end

  def create
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    if params['payjp-token'].blank?
      render :new
    else
      customer = Payjp::Customer.create(
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to user_path(current_user.id)
      else
        render :new
      end
    end
  end

  def show
    if @card.blank?
      redirect_to new_card_path
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end


  def destroy
    if @card.blank?
      render :new
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.destroy
      redirect_to user_path(current_user.id)
    end
  end


  private

  def card_params
    params.require(:card).permit(:user_id, :customer_id, :card_id).merge(user_id: current_user.id)
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

  def set_category
    @parents = Category.where(ancestry: nil)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/edit.html.haml
%section.main-contents
  .single-main
    %section.chapter__container
      %h2.chapter__head 支払い方法
      .payment__main
        .payment__list
          .payment__list__content
            %h3.sub__head クレジットカード
            .card__number
              カード番号
              %br
              = "" + @defauld_card_information.last4
            .expire__date
              有効期限
              %br
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_yaer.to_s.slice(2,3)
              = exp_month + " / " + exp_year
              = form_tag(card_path(current_user.id), method: :delete, id: 'charge-form') do
                %input{ type: "hidden", name: "card_id", value: "" }
                %button.delete__button 解除する
            %toppage_btn
              = link_to 'トップページに戻る', root_path, class:"toppage_btn"

app/views/cards/new.html.haml
= render 'template/header'
= form_tag(cards_path, method: :post, id: 'charge-form') do |f|
  .Payment
    .Payment__title クレジットカード情報入力
    .Payment__text
      %label カード番号
      %span.required 必須
      = text_field_tag "card_number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
    .Payment__expiration
      %label 有効期限
      %span.required 必須
      .Payment__expiration__date
        %select#exp_month{name: "exp_month", type: "text"}
          %option{value: ""} --
          %option{value: "1"}01
          %option{value: "2"}02
          %option{value: "3"}03
          %option{value: "4"}04
          %option{value: "5"}05
          %option{value: "6"}06
          %option{value: "7"}07
          %option{value: "8"}08
          %option{value: "9"}09
          %option{value: "10"}10
          %option{value: "11"}11
          %option{value: "12"}12
        .Exp-text 月
        %select#exp_year{name: "exp_year", type: "text"}
          %option{value: ""} --
          %option{value: "2021"}21
          %option{value: "2022"}22
          %option{value: "2023"}23
          %option{value: "2024"}24
          %option{value: "2025"}25
          %option{value: "2026"}26
          %option{value: "2027"}27
          %option{value: "2028"}28
          %option{value: "2029"}29
        .Exp-text 年
    .Payment__code
      %label セキュリティコード
      %span.required 必須
      = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
    #card_token
    = submit_tag "登録する", id: "token_submit",class:"red_btn","data-turbolinks": false
    .Payment__buttom
      = link_to 'マイページに戻る', user_path(current_user.id), class:"toppage_btn"
= render 'template/footer'

app/views/cards/show.html.haml
= render 'template/header'
.Chapter
  -# .Chapter__head 支払い方法
  .Chapter__title クレジットカード登録情報
  .Chapter__card
    %form.Chapter__card__content
    .Chapter__card__number
      %p クレジットカード番号
      %br
      = "**** **** **** " + @default_card_information.last4
    .Chapter__card__date
      %p 有効期限
      %br
      - exp_month = @default_card_information.exp_month.to_s
      - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
      = exp_month + " / " + exp_year
      = form_tag(card_path(current_user.id), method: :delete, id:'charge-form') do
        %input{ type: "hidden", name: "card_id", value: "" }
        %button.Delete__button 削除する
    .Payment__buttom
      = link_to 'マイページに戻る', user_path(current_user.id), class:"toppage_btn"
= render 'template/footer'